apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.api.pvc.name }}
  labels:
    {{- include "synergychart.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.api.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.api.pvc.size }}
