apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    {{- include "synergychart.labels" . | nindent 4 }}
spec:
  selector:
    app: synergychat-web
  ports:
    - protocol: TCP
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    {{- include "synergychart.labels" . | nindent 4 }}
spec:
  selector:
    app: synergychat-api
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  namespace: {{ .Values.crawler.namespace }}
  labels:
    {{- include "synergychart.labels" . | nindent 4 }}
spec:
  selector:
    app: synergychat-crawler
  ports:
    - protocol: TCP
      port: {{ .Values.crawler.service.port }}
      targetPort: {{ .Values.crawler.service.targetPort }}
